# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC56():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC56(self):
    # Test name: TC_56
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 781x822 | 
    self.driver.set_window_size(781, 822)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtMatkhau | 1234
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | admin
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    # 7 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    # 8 | click | css=#HyperLink5 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    # 9 | click | css=.item-data:nth-child(8) .bt-style-chucnang:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(8) .bt-style-chucnang:nth-child(1)").click()
    # 10 | click | name=ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl01 | 
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl01").click()
    # 11 | type | name=ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl01 | Kính vip
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl01").send_keys("Kính vip")
    # 12 | click | name=ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl02 | 
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl08$ctl02").click()
    # 13 | mouseDownAt | css=html | 911,784
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 14 | mouseMoveAt | css=html | 911,784
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | mouseUpAt | css=html | 911,784
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 16 | click | id=LinkDX | 
    self.driver.find_element(By.ID, "LinkDX").click()
    # 17 | close |  | 
    self.driver.close()
  
