# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC57():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC57(self):
    # Test name: TC_57
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1014x696 | 
    self.driver.set_window_size(1014, 696)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtMatkhau | 1234
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | admin
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    # 7 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    # 8 | click | css=#HyperLink5 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    # 9 | click | id=ContentPlaceHolder1_txtID | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
    # 10 | type | id=ContentPlaceHolder1_txtID | -5
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").send_keys("-5")
    # 11 | type | id=ContentPlaceHolder1_txtTenDM | Kính cường lực
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").send_keys("Kính cường lực")
    # 12 | click | id=ContentPlaceHolder1_LinkButton1 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
    # 13 | click | id=LinkDX | 
    self.driver.find_element(By.ID, "LinkDX").click()
    # 14 | close |  | 
    self.driver.close()
  
