# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC41():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC41(self):
    # Test name: TC41
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1186x700 | 
    self.driver.set_window_size(1186, 700)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtMatkhau | 2005
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("2005")
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | van
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("van")
    # 7 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
