# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC48():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC48(self):
    # Test name: TC48
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1042x700 | 
    self.driver.set_window_size(1042, 700)
    # 3 | click | css=.mySlides:nth-child(1) > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".mySlides:nth-child(1) > img").click()
    # 4 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 5 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | aaaa
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("aaaa")
    # 7 | click | id=ContentPlaceHolder1_txtMatkhau | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    # 8 | type | id=ContentPlaceHolder1_txtMatkhau | aaaa
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("aaaa")
    # 9 | click | css=.khung | 
    self.driver.find_element(By.CSS_SELECTOR, ".khung").click()
    # 10 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
