# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC33():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC33(self):
    # Test name: TC_33
    # Step # | name | target | value
    # 1 | open | /Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1294x741 | 
    self.driver.set_window_size(1294, 741)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtMatkhau | 1234
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | admin
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    # 7 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    # 8 | click | css=#HyperLink1 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink1 > li").click()
    # 9 | click | css=.menu-trai a:nth-child(2) > li | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    # 10 | click | id=ContentPlaceHolder1_DataList1_Image1_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    # 11 | click | css=.chitiet-sp | 
    self.driver.find_element(By.CSS_SELECTOR, ".chitiet-sp").click()
    # 12 | click | id=ContentPlaceHolder1_Datalist1_btnThemVaoGio_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    # 13 | click | id=ContentPlaceHolder1_btnThanhToan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    # 14 | click | id=ContentPlaceHolder1_dtlThongTinUser_txtTen_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").click()
    # 15 | type | id=ContentPlaceHolder1_dtlThongTinUser_txtTen_0 | Nguyễn Đức Hoàng Hiệp
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").send_keys("Nguyễn Đức Hoàng Hiệp")
    # 16 | type | id=ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0 | 0123456789
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0").send_keys("0123456789")
    # 17 | type | id=ContentPlaceHolder1_dtlThongTinUser_txtEmail_0 |   
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtEmail_0").send_keys("  ")
    # 18 | type | id=ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0 |  Hoài Đức, Hà Nội
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").send_keys(" Hoài Đức, Hà Nội")
    # 19 | type | id=ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0 |  Giao hàng cẩn thận!
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys(" Giao hàng cẩn thận!")
    # 20 | click | id=ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
