# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC26():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC26(self):
    # Test name: TC_26
    # Step # | name | target | value
    # 1 | open | /Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1294x741 | 
    self.driver.set_window_size(1294, 741)
    # 3 | click | css=.menu-trai a:nth-child(2) > li | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    # 4 | click | id=ContentPlaceHolder1_DataList1_Image1_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    # 5 | click | id=ContentPlaceHolder1_Datalist1_btnThemVaoGio_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    # 6 | click | id=ContentPlaceHolder1_btnThanhToan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
  
