# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC28():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC28(self):
    # Test name: TC_28
    # Step # | name | target | value
    # 1 | open | /Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1294x741 | 
    self.driver.set_window_size(1294, 741)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtMatkhau | 1234
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    # 6 | type | id=ContentPlaceHolder1_txtTaikhoan | admin
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    # 7 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    # 8 | click | css=#HyperLink1 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink1 > li").click()
    # 9 | click | css=#HyperLink4 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
    # 10 | click | id=ContentPlaceHolder1_btnXoaGioHang | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnXoaGioHang").click()
    # 11 | click | id=ContentPlaceHolder1_btnThanhToan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
  
