# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC01(self):
    # Test name: TC_01
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1366x728 | 
    self.driver.set_window_size(1366, 728)
    # 3 | click | id=LinkDK | 
    self.driver.find_element(By.ID, "LinkDK").click()
    # 4 | close |  | 
    self.driver.close()
  
