# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC03():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_tC03(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.set_window_size(1366, 728)

        self.driver.find_element(By.ID, "LinkDK").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("thuan123")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("thuan123")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Hưng Thuận")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtNamSinh").send_keys("2005-09-04")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(1)").click()

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtEmail").send_keys("thuan205@gmail.com")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtSdt").send_keys("0963053320")

        # ===== FIX LỖI Ở ĐÂY =====
        wait = WebDriverWait(self.driver, 10)
        dia_chi = wait.until(
            EC.visibility_of_element_located((By.ID, "ContentPlaceHolder1_txtDiaChi"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", dia_chi)
        dia_chi.send_keys("Bắc Từ Liêm, Hà Nội")
        # ========================

        self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangky").click()
