# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTC02():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_tC02(self):
        # Test name: TC_02

        # 1 | open
        self.driver.get("http://hauiproj.somee.com/Default.aspx")

        # 2 | setWindowSize
        self.driver.set_window_size(1366, 728)

        # 3 | click | id=LinkDK
        self.driver.find_element(By.ID, "LinkDK").click()

        # 4 | click | id=ContentPlaceHolder1_txtTaiKhoan
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").click()

        # 5 | type | username
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaiKhoan").send_keys("thuan123")

        # 6 | type | password
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatKhau").send_keys("thuan123")

        # ====== FIX LỖI Ở ĐÂY ======
        wait = WebDriverWait(self.driver, 10)
        quay_lai = wait.until(
            EC.element_to_be_clickable((By.LINK_TEXT, "Quay lại"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", quay_lai)
        quay_lai.click()
        # ===========================

        # Không cần close vì teardown_method đã quit()
