# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC11():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC11(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1100, 924)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
  
