# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC16():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC16(self):
    # Test name: TC_16
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1048x945 | 
    self.driver.set_window_size(1048, 945)
    # 3 | click | css=#HyperLink2 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    # 4 | click | id=ContentPlaceHolder1_DataList1_Image1_6 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_6").click()
    # 5 | click | id=ContentPlaceHolder1_Datalist1_txtSoLuong_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    # 6 | type | id=ContentPlaceHolder1_Datalist1_txtSoLuong_0 | abc
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("abc")
    # 7 | click | id=ContentPlaceHolder1_Datalist1_btnThemVaoGio_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    # 8 | assertText | id=ContentPlaceHolder1_Datalist1_lblThongBao_0 | Số lượng mua không hợp lệ!
    assert self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_lblThongBao_0").text == "Số lượng mua không hợp lệ!"
  
