# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC24():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC24(self):
    # Test name: TC_24
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1100x924 | 
    self.driver.set_window_size(1100, 924)
    # 3 | click | id=LinkDN | 
    self.driver.find_element(By.ID, "LinkDN").click()
    # 4 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 5 | type | id=ContentPlaceHolder1_txtTaikhoan | abc
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    # 6 | click | id=ContentPlaceHolder1_txtMatkhau | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    # 7 | type | id=ContentPlaceHolder1_txtMatkhau | abc
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("abc")
    # 8 | click | id=ContentPlaceHolder1_txtTaikhoan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    # 9 | click | id=ContentPlaceHolder1_btDangnhap | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    # 10 | click | css=#HyperLink2 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    # 11 | click | id=ContentPlaceHolder1_DataList1_Image1_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    # 12 | click | id=ContentPlaceHolder1_Datalist1_btnThemVaoGio_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    # 13 | click | id=ContentPlaceHolder1_btnThanhToan | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
  
