# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC20():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC20(self):
    # Test name: TC_20
    # Step # | name | target | value
    # 1 | open | http://hauiproj.somee.com/Default.aspx | 
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    # 2 | setWindowSize | 1100x924 | 
    self.driver.set_window_size(1100, 924)
    # 3 | click | css=#HyperLink2 > li | 
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    # 4 | click | id=ContentPlaceHolder1_DataList1_Image1_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    # 5 | click | id=ContentPlaceHolder1_Datalist1_btnThemVaoGio_0 | 
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    # 6 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 7 | click | css=td:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(6)").click()
    # 8 | type | id=ContentPlaceHolder1_gvGioHang_txtSoLuong_0 | 999999
    self.driver.find_element(By.ID, "ContentPlaceHolder1_gvGioHang_txtSoLuong_0").send_keys("999999")
    # 9 | click | css=td:nth-child(8) > .bt-style-chucnang | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(8) > .bt-style-chucnang").click()
  
